const BASE='https://mabvxdcpmfdzrqlgkxqn.supabase.co';
const KEY='sb_publishable_Fh0fWwz6kCfMlcgYCsTJOA_eZmHsib4';
const API=BASE+'/functions/v1/v1-runtime';
const state={session:readSession(),me:null,overview:null,page:'home',detail:null,invite:sessionStorage.getItem('dp_invite')||'',busy:false,sessionExpired:false};
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>d?new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'short',day:'numeric'}).format(new Date(d)):'미정';
const labels={ACTIVE:'활성',OPEN:'진행 중',SUBMITTED:'신청 완료',APPROVED:'승인',STARTED:'참여 중',COMPLETED:'완료',CONNECTED:'연결 완료',PENDING:'대기',VERIFIED:'인증 완료',OWNER:'운영자',MEMBER:'구성원',OWNER_VET:'원장',DIRECTOR:'원장',VETERINARIAN:'수의사',VET:'수의사',STAFF:'직원',STUDENT:'수의대생',ENTERPRISE_USER:'기업회원',GUARDIAN:'보호자',ADMIN:'관리자',GENERAL:'일반 지원',PRODUCT:'제품·샘플',DEMO:'장비 데모',SPONSORSHIP:'협찬·스폰서십',MANAGEMENT:'경영·운영 지원'};
const label=x=>labels[x]||x||'-';
function readSession(){try{return JSON.parse(sessionStorage.getItem('dp_session')||'null')}catch{return null}}
class ClientError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code}}
async function auth(path,body){const r=await fetch(BASE+'/auth/v1/'+path,{method:'POST',headers:{apikey:KEY,'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new ClientError(r.status,j.error||'',j.msg||j.error_description||j.message||'인증에 실패했습니다.');return j}
async function api(path,{method='GET',body,idempotency}={}){const r=await fetch(API+path,{method,headers:{authorization:'Bearer '+state.session?.access_token,apikey:KEY,'content-type':'application/json','x-request-id':crypto.randomUUID(),...(idempotency?{'x-idempotency-key':idempotency}:{})},body:body?JSON.stringify(body):undefined});let j={};try{j=await r.json()}catch{}if(!r.ok){if(r.status===401)expireSession();throw new ClientError(r.status,j.error?.code||'',j.error?.message||'요청을 처리하지 못했습니다.')}return j.data}
function expireSession(){sessionStorage.removeItem('dp_session');state.session=null;state.me=null;state.overview=null;state.sessionExpired=true}
function setMsg(m,ok=false){const e=$('#msg');if(e){e.className=ok?'notice success':'notice error';e.textContent=m}}
function badge(value){return `<span class="badge badge-${esc(String(value||'').toLowerCase())}">${esc(label(value))}</span>`}
function empty(title,body='새로운 내용이 생기면 이곳에 표시됩니다.'){return `<div class="empty"><div class="empty-icon">＋</div><strong>${esc(title)}</strong><p>${esc(body)}</p></div>`}
function loading(){return `<div class="loading"><span></span><p>정보를 불러오는 중입니다.</p></div>`}
function errorView(x){const denied=x?.status===403;return `<div class="state-panel ${denied?'deny':'error'}"><strong>${denied?'접근 권한이 없습니다':'정보를 불러오지 못했습니다'}</strong><p>${esc(denied?'현재 역할과 소속으로 허용되지 않은 기능입니다.':x?.message||'잠시 후 다시 시도해 주세요.')}</p><button class="secondary" data-retry>다시 시도</button></div>`}
async function login(e){e.preventDefault();setMsg('');try{const d=await auth('token?grant_type=password',{email:$('#email').value,password:$('#password').value});state.session=d;state.sessionExpired=false;sessionStorage.setItem('dp_session',JSON.stringify(d));await load()}catch(x){setMsg(x.message)}}
async function signup(e){e.preventDefault();try{const d=await auth('signup',{email:$('#email').value,password:$('#password').value,data:{display_name:$('#name').value}});if(!d.access_token)throw new Error('이메일 확인 후 로그인해 주세요.');state.session=d;sessionStorage.setItem('dp_session',JSON.stringify(d));const b=await api('/profile/bootstrap',{method:'POST',body:{displayName:$('#name').value,role:$('#role').value}});state.invite=b.invitationToken||'';sessionStorage.setItem('dp_invite',state.invite);await load()}catch(x){setMsg(x.message)}}
async function activate(){try{await api('/activation',{method:'POST',body:{invitationToken:state.invite},idempotency:'activate:'+state.session.user.id});await load()}catch(x){setMsg(x.message)}}
async function logout(){try{await auth('logout',{})}catch{}sessionStorage.clear();state.session=null;state.me=null;state.overview=null;state.sessionExpired=false;state.page='home';render()}
async function load(){state.busy=true;render();try{state.me=await api('/me');state.overview=state.me?.state==='ACTIVE'?await api('/overview'):null;state.busy=false;render()}catch(x){state.busy=false;if(!state.session)return render();state.me=null;render(errorView(x))}}
async function refreshOverview(){state.busy=true;render();try{state.overview=await api('/overview');state.busy=false;render()}catch(x){state.busy=false;render(errorView(x))}}
function authView(){return `<div class="auth-wrap"><div class="auth-card"><div class="logo-mark">D</div><div class="brand auth-brand">DoctorPet</div><h1>병원 네트워크 로그인</h1><p class="muted">동물병원 캠페인과 무료지원 서비스를 이용하세요.</p>${state.sessionExpired?'<div class="notice error">로그인이 만료되었습니다. 다시 로그인해 주세요.</div>':''}<div id="msg"></div><form id="login"><label>이메일<input id="email" type="email" autocomplete="username" placeholder="이메일 주소" required></label><label>비밀번호<input id="password" type="password" autocomplete="current-password" minlength="10" placeholder="비밀번호" required></label><button class="primary full-button" type="submit">로그인</button></form><details class="dev-signup"><summary>DEV 테스트 회원가입</summary><form id="signup"><input id="name" placeholder="이름" required><select id="role"><option>VET</option><option>STAFF</option><option>STUDENT</option><option>ENTERPRISE_USER</option><option>GUARDIAN</option></select><button class="secondary" type="submit">가입하기</button></form></details></div></div>`}
const hospitalNav=[['home','홈','⌂'],['hospital','내 병원','✚'],['campaign','캠페인','▣'],['support','무료지원','♡'],['matching','매칭','⇄'],['space','내 공간','⌘'],['account','내 계정','○'],['more','더보기','•••']];
const legacyNav=[['home','홈','⌂'],['hospital','병원방','✚'],['enterprise','기업방','▦'],['campaign','캠페인','▣'],['support','무료지원','♡'],['matching','매칭','⇄'],['admin','관리자','◇']];
function isHospitalUser(){return state.me?.roles?.includes('VET')||state.me?.affiliations?.some(a=>a.organization_type==='HOSPITAL')}
function navItems(){return isHospitalUser()?hospitalNav:legacyNav}
function shell(content){const items=navItems();return `<div class="shell"><header class="top"><div class="top-brand"><span class="logo-mark small">D</span><span class="brand">DoctorPet</span><span class="dev-tag">DEV</span></div><div class="profile-chip"><span>${esc(state.me?.profile?.display_name||'회원')}</span>${badge(state.me?.state)}</div></header><div class="layout"><nav class="nav" aria-label="주 메뉴">${items.map(([k,v,i])=>`<button data-page="${k}" class="${state.page===k?'active':''}"><span>${i}</span>${v}</button>`).join('')}</nav><main class="main">${content}</main></div></div>`}
function pageTitle(title,desc,action=''){return `<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${action}</div>`}
function metric(title,value,note,page){return `<button class="metric-card" ${page?`data-page="${page}"`:''}><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></button>`}
function primaryHospital(){return state.me?.affiliations?.find(a=>a.organization_type==='HOSPITAL'&&a.status==='ACTIVE'&&a.verification_status==='VERIFIED'&&a.is_primary)||state.me?.affiliations?.find(a=>a.organization_type==='HOSPITAL'&&a.status==='ACTIVE'&&a.verification_status==='VERIFIED')}
function applicationFor(campaignId){return state.overview?.applications?.find(a=>a.campaign_id===campaignId)}
function hospitalHome(){const hospital=primaryHospital();const open=(state.overview?.campaigns||[]).filter(c=>c.status==='OPEN');const applications=state.overview?.applications||[];const participations=applications.filter(a=>a.participation_status);const support=state.overview?.support||[];const matched=(state.overview?.matching||[]).filter(m=>m.result_status==='CONNECTED'||m.status==='COMPLETED');const alerts=[applications[0]&&`최근 캠페인 신청은 ${label(applications[0].participation_status||applications[0].status)} 상태입니다.`,support[0]&&`무료지원 요청이 ${label(support[0].status)} 상태입니다.`,matched[0]&&`${matched[0].enterprise_name||'파트너 기업'} 매칭 결과를 확인해 주세요.`].filter(Boolean);return `${pageTitle('안녕하세요, '+(state.me.profile?.display_name||'원장님')+'님','오늘의 병원 운영 현황을 한눈에 확인하세요.')}<section class="hospital-hero"><div><span class="eyebrow">내 병원</span><h2>${esc(hospital?.name||'소속 병원 확인 필요')}</h2><p>${hospital?`${esc(label(hospital.position_code||'소속'))} · ${esc(label(hospital.verification_status))}`:'인증된 병원 소속이 없습니다.'}</p></div><button class="light-button" data-page="hospital">병원 정보 보기 →</button></section><div class="metrics five">${metric('진행 캠페인',open.length+'건','신청 가능한 캠페인','campaign')}${metric('내 신청',applications.length+'건',applications[0]?label(applications[0].status):'신청 내역 없음','campaign')}${metric('참여 현황',participations.length+'건',participations[0]?label(participations[0].participation_status):'참여 전','campaign')}${metric('무료지원',support.length+'건',support[0]?label(support[0].status):'요청 내역 없음','support')}${metric('매칭 결과',matched.length+'건',matched[0]?label(matched[0].result_status):'매칭 대기','matching')}</div><section class="section"><div class="section-head"><h2>주요 알림</h2></div>${alerts.length?`<div class="alert-list">${alerts.map(x=>`<div><span>●</span>${esc(x)}</div>`).join('')}</div>`:empty('새로운 알림이 없습니다.','캠페인 신청과 지원 요청의 진행 소식을 알려드립니다.')}</section><section class="section"><div class="section-head"><h2>빠른 시작</h2></div><div class="quick-grid"><button data-page="campaign"><b>캠페인 찾기</b><span>병원에 맞는 캠페인 확인</span></button><button data-page="support"><b>무료지원 요청</b><span>제품·샘플·데모 지원 신청</span></button><button data-page="matching"><b>매칭 현황</b><span>연결된 기업과 진행상태 확인</span></button></div></section>`}
function hospitalPage(){const affiliations=(state.me.affiliations||[]).filter(a=>a.organization_type==='HOSPITAL');const rooms=(state.me.rooms||[]).filter(r=>r.room_type?.includes('HOSPITAL'));return `${pageTitle('내 병원','인증된 소속과 병원 전용 공간을 확인합니다.')}<div class="content-grid"><section class="panel"><div class="section-head"><h2>병원·소속 정보</h2>${affiliations[0]?badge(affiliations[0].verification_status):''}</div>${affiliations.length?affiliations.map(a=>`<article class="info-card"><div><span class="eyebrow">${a.is_primary?'대표 소속':'소속 병원'}</span><h3>${esc(a.name)}</h3></div><dl><div><dt>현재 역할</dt><dd>${esc(label(a.position_code||'소속 구성원'))}</dd></div><div><dt>지역</dt><dd>${esc(a.region_code||'정보 없음')}</dd></div><div><dt>소속 상태</dt><dd>${badge(a.status)}</dd></div><div><dt>인증 상태</dt><dd>${badge(a.verification_status)}</dd></div></dl></article>`).join(''):empty('인증된 병원 소속이 없습니다.')}</section><section class="panel"><div class="section-head"><h2>병원방</h2><span>${rooms.length}개</span></div>${rooms.length?`<div class="stack">${rooms.map(r=>`<button class="list-card" data-room="${esc(r.id)}"><span class="list-icon">병</span><span><b>${esc(primaryHospital()?.name||'병원')} 전용 공간</b><small>${esc(label(r.membership_role))} · ${label(r.status)}</small></span><i>›</i></button>`).join('')}</div>`:empty('참여 중인 병원방이 없습니다.')}</section></div><section class="panel permissions"><div class="section-head"><h2>현재 역할</h2></div><div class="chip-row">${(state.me.roles||[]).map(x=>`<span class="role-chip">${esc(label(x))}</span>`).join('')}</div><div class="slot-row"><div><b>병원 구성원과 권한</b><p>구성원 관리 화면은 다음 단계에서 연결됩니다.</p></div><span class="slot-badge">준비 중</span></div></section>`}
function roomDetailView(room){return `${pageTitle('병원방 상세','내 소속과 역할에 따라 이용할 수 있는 병원 전용 공간입니다.','<button class="secondary" data-page="hospital">← 목록</button>')}<section class="panel detail-panel"><span class="eyebrow">병원 전용 공간</span><h2>${esc(primaryHospital()?.name||'병원방')}</h2><p class="lead">캠페인, 무료지원과 매칭 현황을 병원 구성원과 함께 확인하는 공간입니다.</p><dl><div><dt>공간</dt><dd>병원방</dd></div><div><dt>내 역할</dt><dd>${esc(label(room.membership_role))}</dd></div><div><dt>이용 상태</dt><dd>${badge(room.status)}</dd></div></dl><div class="quick-grid compact"><button data-page="campaign"><b>캠페인</b><span>신청과 참여 현황</span></button><button data-page="support"><b>무료지원</b><span>요청과 진행상태</span></button><button data-page="matching"><b>매칭</b><span>기업 연결 결과</span></button></div></section>`}
function campaignCard(c){const a=applicationFor(c.id);return `<article class="campaign-card"><div class="campaign-top"><span class="eyebrow">${esc(c.enterprise_name||'파트너 기업')}</span>${badge(c.status)}</div><h3>${esc(c.name)}</h3><p>${esc(typeof c.brief==='object'?(c.brief?.summary||c.brief?.description||'동물병원을 위한 캠페인입니다.'):(c.brief||'동물병원을 위한 캠페인입니다.'))}</p><div class="date-row"><span>${fmt(c.starts_at)} 시작</span><span>${c.ends_at?fmt(c.ends_at)+' 종료':'종료일 미정'}</span></div><div class="card-actions">${a?`<span class="application-state">${label(a.participation_status||a.status)}</span>`:''}<button class="secondary" data-campaign="${esc(c.id)}">상세 보기</button></div></article>`}
function campaignsPage(){const rows=state.overview?.campaigns||[];return `${pageTitle('동물병원 캠페인','병원에 맞는 캠페인을 확인하고 바로 신청하세요.')}<div class="filter-row"><button class="filter active">전체 ${rows.length}</button><button class="filter">진행 중 ${rows.filter(x=>x.status==='OPEN').length}</button><span class="spacer"></span><span class="muted">내 신청 ${(state.overview?.applications||[]).length}건</span></div>${rows.length?`<div class="campaign-grid">${rows.map(campaignCard).join('')}</div>`:empty('현재 진행 중인 캠페인이 없습니다.')}`}
function campaignDetail(c){const a=applicationFor(c.id);const canApply=c.status==='OPEN'&&!a;const brief=typeof c.brief==='object'?c.brief:{};return `${pageTitle('캠페인 상세','신청 조건과 진행상태를 확인하세요.','<button class="secondary" data-page="campaign">← 목록</button>')}<article class="panel detail-panel"><div class="campaign-top"><span class="eyebrow">${esc(c.enterprise_name||'파트너 기업')}</span>${badge(c.status)}</div><h2>${esc(c.name)}</h2><p class="lead">${esc(typeof c.brief==='object'?(brief.summary||brief.description||'등록된 상세 설명이 없습니다.'):(c.brief||'등록된 상세 설명이 없습니다.'))}</p><dl><div><dt>캠페인 유형</dt><dd>${esc(labels[c.campaign_type]||'동물병원 캠페인')}</dd></div><div><dt>진행 기간</dt><dd>${fmt(c.starts_at)} — ${c.ends_at?fmt(c.ends_at):'미정'}</dd></div><div><dt>참여 대상</dt><dd>${esc(brief.target||'참여 가능한 동물병원')}</dd></div><div><dt>제공 혜택</dt><dd>${esc(brief.benefit||brief.benefits||'캠페인 상세 혜택을 확인해 주세요.')}</dd></div><div><dt>신청 상태</dt><dd>${a?badge(a.status):'미신청'}</dd></div><div><dt>참여 상태</dt><dd>${a?.participation_status?badge(a.participation_status):'참여 전'}</dd></div></dl><div class="detail-action">${canApply?`<button class="primary" id="applyCampaign" data-id="${esc(c.id)}">이 캠페인 신청하기</button>`:a?`<div class="notice success">신청이 접수되었습니다. 현재 상태: ${esc(label(a.participation_status||a.status))}</div>`:`<div class="notice">현재 신청할 수 없는 캠페인입니다.</div>`}</div></article>`}
function supportPage(){const hospital=primaryHospital();const rows=state.overview?.support||[];return `${pageTitle('동물병원 무료지원센터','제품·샘플·데모·운영 지원을 요청하세요.')}<div class="content-grid support-layout"><section class="panel form-panel"><div class="section-head"><h2>새 지원 요청</h2></div>${hospital?`<div class="selected-hospital"><span>신청 병원</span><b>${esc(hospital.name)}</b>${badge(hospital.verification_status)}</div><form id="supportForm"><label>지원 유형<select id="supportType"><option value="GENERAL">일반 지원</option><option value="PRODUCT">제품·샘플</option><option value="DEMO">장비 데모</option><option value="SPONSORSHIP">협찬·스폰서십</option><option value="MANAGEMENT">경영·운영 지원</option></select></label><label>요청 제목<input id="supportTitle" maxlength="120" placeholder="필요한 지원을 한 줄로 입력하세요" required></label><label>요청 내용<textarea id="supportDesc" maxlength="1000" rows="6" placeholder="필요한 제품, 수량, 일정 등을 알려주세요" required></textarea></label><button class="primary full-button" type="submit">지원 요청 등록</button></form>`:`<div class="state-panel deny"><strong>인증된 병원 소속이 필요합니다.</strong><p>병원 소속 인증이 완료되면 무료지원을 요청할 수 있습니다.</p></div>`}</section><section class="panel"><div class="section-head"><h2>내 요청 현황</h2><span>${rows.length}건</span></div>${rows.length?`<div class="stack">${rows.map(r=>`<button class="list-card support-card" data-support="${esc(r.id)}"><span><b>${esc(r.title||r.request_type)}</b><small>${fmt(r.requested_at)} · ${esc(label(r.request_type))}</small></span>${badge(r.status)}<i>›</i></button>`).join('')}</div>`:empty('아직 등록한 지원 요청이 없습니다.','첫 지원 요청을 작성하면 진행상태를 이곳에서 확인할 수 있습니다.')}</section></div>`}
function supportDetail(r){const match=(state.overview?.matching||[]).find(m=>m.support_request_id===r.id);return `${pageTitle('지원 요청 상세','요청 내용과 매칭 진행상태입니다.','<button class="secondary" data-page="support">← 목록</button>')}<section class="panel detail-panel"><div class="campaign-top"><span class="eyebrow">${esc(label(r.request_type))}</span>${badge(r.status)}</div><h2>${esc(r.title||'지원 요청')}</h2><p class="lead">${esc(r.description||'등록된 상세 내용이 없습니다.')}</p><dl><div><dt>신청 병원</dt><dd>${esc(primaryHospital()?.name||'-')}</dd></div><div><dt>신청일</dt><dd>${fmt(r.requested_at)}</dd></div><div><dt>매칭 상태</dt><dd>${match?badge(match.status):'매칭 대기'}</dd></div></dl>${match?`<button class="secondary" data-page="matching">매칭 결과 보기 →</button>`:''}</section>`}
function matchingPage(){const rows=state.overview?.matching||[];return `${pageTitle('기업 매칭','지원 요청별 기업 연결 결과를 확인하세요.')}<section class="panel"><div class="section-head"><h2>매칭 현황</h2><span>${rows.length}건</span></div>${rows.length?`<div class="stack">${rows.map(m=>`<button class="matching-card" data-matching="${esc(m.id)}"><span class="match-flow"><i>요청</i><em></em><i>매칭</i><em></em><i class="${m.result_status==='CONNECTED'?'done':''}">연결</i></span><span class="match-copy"><b>${esc(m.support_title||'지원 요청')}</b><small>${esc(m.enterprise_name||'기업 검토 중')} · ${fmt(m.opened_at)}</small></span>${badge(m.result_status||m.status)}<strong>›</strong></button>`).join('')}</div>`:empty('진행 중인 매칭이 없습니다.','무료지원 요청이 접수되면 매칭 진행상태가 표시됩니다.')}</section>`}
function matchingDetail(m){return `${pageTitle('매칭 상세','지원 요청과 연결 기업의 현재 상태입니다.','<button class="secondary" data-page="matching">← 목록</button>')}<section class="panel detail-panel"><div class="campaign-top"><span class="eyebrow">MATCHING</span>${badge(m.result_status||m.status)}</div><h2>${esc(m.support_title||'지원 요청 매칭')}</h2><div class="match-steps"><div class="done"><b>1</b><span>지원 요청<small>접수 완료</small></span></div><div class="${m.status?'done':''}"><b>2</b><span>기업 매칭<small>${esc(m.enterprise_name||'검토 중')}</small></span></div><div class="${m.result_status==='CONNECTED'?'done':''}"><b>3</b><span>연결 결과<small>${esc(label(m.result_status||'PENDING'))}</small></span></div></div><dl><div><dt>매칭 기업</dt><dd>${esc(m.enterprise_name||'선정 중')}</dd></div><div><dt>후보 상태</dt><dd>${esc(label(m.candidate_status||'PENDING'))}</dd></div><div><dt>연결 상태</dt><dd>${badge(m.result_status||m.status)}</dd></div><div><dt>연결일</dt><dd>${fmt(m.connected_at)}</dd></div></dl></section>`}
function spacePage(){return `${pageTitle('내 공간','앞으로 연결될 개인·직군·그룹 공간의 진입점입니다.')}<div class="space-grid"><article class="slot-card"><span>개인</span><h2>원장 개인방</h2><p>내 업무와 활동을 모아보는 개인 공간입니다.</p><b>준비 중</b></article><article class="slot-card"><span>수의사</span><h2>수의사방</h2><p>수의사 정보·교육·네트워크를 위한 공간입니다.</p><b>준비 중</b></article><article class="slot-card"><span>AI</span><h2>내 비서방</h2><p>향후 개인 업무와 알림을 돕는 공간입니다.</p><b>준비 중</b></article><article class="slot-card"><span>네트워크</span><h2>그룹·초대·추천</h2><p>그룹과 추천 관계를 확인하는 공간입니다.</p><b>준비 중</b></article></div><div class="notice">현재는 진입 구조만 제공하며, 준비 중인 기능은 실제 요청이나 데이터 변경을 수행하지 않습니다.</div>`}
function morePage(){return `${pageTitle('더보기','병원 운영과 계정 메뉴를 확인하세요.')}<div class="more-list"><button data-page="hospital"><span>✚</span><b>내 병원</b><i>›</i></button><button data-page="matching"><span>⇄</span><b>매칭</b><i>›</i></button><button data-page="account"><span>○</span><b>내 계정</b><i>›</i></button></div>`}
function accountPage(){const hospital=primaryHospital();return `${pageTitle('내 계정','회원정보와 현재 소속을 확인합니다.')}<section class="panel account-panel"><div class="avatar">${esc((state.me.profile?.display_name||'회').slice(0,1))}</div><h2>${esc(state.me.profile?.display_name||'회원')}</h2><p>${esc(state.me.profile?.email||'')}</p><dl><div><dt>회원 상태</dt><dd>${badge(state.me.state)}</dd></div><div><dt>역할</dt><dd>${esc((state.me.roles||[]).map(label).join(', '))}</dd></div><div><dt>소속 병원</dt><dd>${esc(hospital?.name||'없음')}</dd></div><div><dt>병원 인증</dt><dd>${hospital?badge(hospital.verification_status):'-'}</dd></div></dl><button class="danger-button" id="accountLogout">로그아웃</button></section>`}
function legacyTable(rows,cols){return !rows?.length?empty('표시할 데이터가 없습니다.'): `<div class="table-wrap"><table><thead><tr>${cols.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(x=>`<td>${esc(typeof r[x]==='object'?JSON.stringify(r[x]):r[x])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
async function legacyPage(kind){try{const d=kind==='admin'?await api('/admin/dashboard'):state.overview||await api('/overview');if(kind==='admin')return `<section class="hospital-hero"><div><h2>관리자 대시보드</h2><p>Scope가 확인된 ADMIN 전용</p></div></section><div class="metrics">${Object.entries(d.kpi).map(([k,v])=>metric(k,v,'')).join('')}</div><section class="panel">${legacyTable(d.persons,['display_name','email','status','state'])}${legacyTable(d.hospitals,['name','status','verification_status'])}${legacyTable(d.enterprises,['name','status','verification_status'])}${legacyTable(d.agreements,['agreement_type','status','signed_at'])}${legacyTable(d.acquisition,['source_type','source_key','channel','occurred_at'])}${legacyTable(d.reconciliation,['status','discrepancy','created_at'])}</section>`;if(kind==='campaign')return campaignsPage();if(kind==='support')return supportPage();if(kind==='matching')return matchingPage();return `${pageTitle(kind==='hospital'?'병원방':'기업방','허용된 Affiliation과 Room만 표시됩니다.')}<section class="panel">${legacyTable(state.me.affiliations,['name','organization_type','position_code','status'])}${legacyTable(state.me.rooms,['room_type','membership_role','status'])}</section>`}catch(x){return errorView(x)}}
function hospitalContent(){if(state.detail?.type==='room')return roomDetailView(state.detail.data);if(state.detail?.type==='campaign')return campaignDetail(state.detail.data);if(state.detail?.type==='support')return supportDetail(state.detail.data);if(state.detail?.type==='matching')return matchingDetail(state.detail.data);if(state.page==='home')return hospitalHome();if(state.page==='hospital')return hospitalPage();if(state.page==='campaign')return campaignsPage();if(state.page==='support')return supportPage();if(state.page==='matching')return matchingPage();if(state.page==='space')return spacePage();if(state.page==='account')return accountPage();if(state.page==='more')return morePage();return hospitalHome()}
async function render(override){const root=$('#app');if(!state.session){root.innerHTML=authView();$('#login').onsubmit=login;$('#signup').onsubmit=signup;return}if(state.busy){root.innerHTML=shell(loading());bindShell();return}if(override){root.innerHTML=shell(override);bindShell();return}if(!state.me){root.innerHTML=shell('<div class="state-panel"><strong>회원 연결을 확인하고 있습니다.</strong></div>');bindShell();return}if(state.me.state!=='ACTIVE'){root.innerHTML=shell(`<section class="panel activation"><h1>회원 활성화가 필요합니다.</h1><p>초대 승인을 완료하면 병원 서비스를 이용할 수 있습니다.</p><div id="msg"></div><button id="activate" class="primary" ${state.invite?'':'disabled'}>ACTIVE 전환</button></section>`);bindShell();if($('#activate'))$('#activate').onclick=activate;return}let content=isHospitalUser()?hospitalContent():await legacyPage(state.page);root.innerHTML=shell(content);bindShell();bindPage()}
function bindShell(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.detail=null;render()});document.querySelector('[data-retry]')?.addEventListener('click',load)}
function bindPage(){document.querySelectorAll('[data-room]').forEach(b=>b.onclick=async()=>{state.busy=true;render();try{state.detail={type:'room',data:await api('/rooms/'+b.dataset.room)};state.busy=false;render()}catch(x){state.busy=false;render(errorView(x))}});document.querySelectorAll('[data-campaign]').forEach(b=>b.onclick=()=>{state.detail={type:'campaign',data:state.overview.campaigns.find(x=>x.id===b.dataset.campaign)};render()});document.querySelectorAll('[data-support]').forEach(b=>b.onclick=()=>{state.detail={type:'support',data:state.overview.support.find(x=>x.id===b.dataset.support)};render()});document.querySelectorAll('[data-matching]').forEach(b=>b.onclick=()=>{state.detail={type:'matching',data:state.overview.matching.find(x=>x.id===b.dataset.matching)};render()});$('#applyCampaign')?.addEventListener('click',applyCampaign);$('#supportForm')?.addEventListener('submit',submitSupport);$('#accountLogout')?.addEventListener('click',logout)}
async function applyCampaign(){const id=$('#applyCampaign').dataset.id;if(!confirm('이 캠페인에 신청하시겠습니까?'))return;try{await api('/commands',{method:'POST',idempotency:'apply:'+state.me.id+':'+id,body:{commandType:'APPLY_CAMPAIGN',payload:{campaignId:id}}});state.detail=null;await refreshOverview()}catch(x){alert(x.message)}}
async function submitSupport(e){e.preventDefault();const hospital=primaryHospital();if(!hospital)return;try{const result=await api('/commands',{method:'POST',idempotency:'support:'+crypto.randomUUID(),body:{commandType:'CREATE_SUPPORT_REQUEST',payload:{hospitalId:hospital.hospital_id,title:$('#supportTitle').value,description:$('#supportDesc').value,requestType:$('#supportType').value}}});await refreshOverview();state.detail={type:'support',data:state.overview.support.find(x=>x.id===result.resourceId)||state.overview.support[0]};render()}catch(x){alert(x.message)}}
render();if(state.session)load();
